USE ORG ;
SELECT * FROM Bonus ;

-- AVG SALLARY PER DEPARTMENT
SELECT DEPARTMENT ,MIN(SALLARY) FROM Worker GROUP BY DEPARTMENT ;

-- HAVING IN SIDE GROUP BY
SELECT DEPARTMENT, COUNT(DEPARTMENT)FROM Worker GROUP BY DEPARTMENT HAVING COUNT(DEPARTMENT) >= 1;

REPLACE INTO  Worker (WORKER_ID,FIRST_NAME,LAST_NAME,SALLARY,JOINING_DATE,DEPARTMENT) VALUES(1,'Rohit','Tiwari',43000,'2022-01-13 00:23:34','HR');
INSERT INTO Worker (WORKER_ID,FIRST_NAME,LAST_NAME,SALLARY,JOINING_DATE,DEPARTMENT) VALUES(81,'Rohit','Tiwari',43000,'2022-01-13 00:23:34','HR');
DELETE FROM Worker WHERE WORKER_ID = 81 ;

REPLACE INTO  Worker  SET WORKER_ID = 80 ,FIRST_NAME = 'RAHYK' ,LAST_NAME = 'Rhhd' , SALLARY = 345566 ;
-- INNER JOIN
SELECT Worker.WORKER_ID  ,Bonus.WORKER_REF_ID FROM Worker INNER JOIN Bonus ON Worker.WORKER_ID= Bonus.WORKER_REF_ID ;

-- LEFT JOINT
SELECT Worker.WORKER_ID  ,Bonus.WORKER_REF_ID FROM Worker LEFT JOIN Bonus ON Worker.WORKER_ID= Bonus.WORKER_REF_ID ;
-- RIGHT JOIN 
SELECT Worker.WORKER_ID  ,Bonus.WORKER_REF_ID FROM Worker RIGHT JOIN Bonus ON Worker.WORKER_ID= Bonus.WORKER_REF_ID ;

-- CROSS JOIN 
SELECT Worker.WORKER_ID ,Worker.FIRST_NAME ,Bonus.WORKER_REF_ID FROM Worker  CROSS JOIN Bonus WHERE  Worker.WORKER_ID= Bonus.WORKER_REF_ID ;
